name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Python Libraries
        run: |
          pip3 install numpy
          pip3 install sklearn
          sudo apt-get install python2
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          python2 get-pip.py
          pip2 install numpy
          sudo update-alternatives --install /usr/bin/javapackager javapackager ${{ env.JAVA_HOME }}/bin/javapackager 100 --slave /usr/share/man/man1/javapackager.1 javapackager.1 ${{ env.JAVA_HOME }}/man/man1/javapackager.1

      - run: sbt -v update compile
      - run: sbt -v test
